# Generated by Django 4.2.2 on 2023-07-18 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_campaign_station'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campreport',
            old_name='campaign_id',
            new_name='campaign',
        ),
    ]
