# Generated by Django 4.2.2 on 2023-07-18 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_campaign_id_campreport_campaign'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campreport',
            old_name='campaign',
            new_name='campaign_id',
        ),
    ]
