# Generated by Django 4.2.2 on 2023-07-22 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_household_patient_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='household',
            name='patient_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.patient'),
        ),
    ]
