# Generated by Django 4.2.2 on 2023-07-23 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_household_patient_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='follow_up',
            field=models.BooleanField(),
        ),
    ]
