# Generated by Django 4.2.2 on 2023-08-25 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_preventive_date_reported'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='date_created',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='campreport',
            name='date_created',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='date_created',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='opening_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='morbidity',
            name='date_created',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='mortality',
            name='date_created',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='opening_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='preventive',
            name='date_reported',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='station',
            name='date_created',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='date_created',
            field=models.DateField(),
        ),
    ]
