# Generated by Django 3.2.18 on 2023-05-07 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_date', models.DateField(auto_now_add=True, null=True)),
                ('mode_of_diagnosis', models.CharField(choices=[('New Diagnosis', 'New Diagnosis'), ('Follow Up Diangosis', 'Follow Up Diagnosis')], max_length=50)),
                ('dianosis_type', models.CharField(choices=[('RDT', 'RDT'), ('Microscopy', 'Microscopy'), ('PCR', 'PCR')], max_length=50)),
                ('results', models.CharField(choices=[('Positive', 'Positive'), ('Negative', 'Negative')], max_length=50)),
                ('malaria_type', models.CharField(choices=[('P. falciparum', 'P. falciparum'), ('P. vivae', 'P. vivae'), ('P. ovale', 'P. ovale'), ('P. malariae', 'P. malariae')], max_length=50)),
                ('parasitemia_load', models.CharField(max_length=50)),
                ('comment', models.TextField(max_length=5000)),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=50)),
                ('age', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('family_size', models.IntegerField()),
                ('no_of_children', models.IntegerField()),
                ('sleeping_in_screen', models.BooleanField()),
                ('use_of_insecticide', models.BooleanField()),
                ('opening_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('Hospital', 'Hospital'), ('Clinic', 'Clinic')], max_length=50)),
                ('gis_location', models.CharField(max_length=50)),
                ('address', models.TextField(max_length=200)),
                ('supervisor', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=200)),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=200, null=True)),
                ('phone', models.IntegerField(null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment_type', models.CharField(choices=[('ACTs', 'ACTs'), ('Non ACTs', 'Non ACTs'), ('Others', 'Others')], max_length=50)),
                ('treatment_period', models.CharField(choices=[('3 Days', '3 Days'), ('7 Days', '7 Days'), ('14 Days', '14 Days')], max_length=50)),
                ('further_treatment', models.BooleanField()),
                ('comment', models.TextField(max_length=5000)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('follow_up', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.diagnosis')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.patient')),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='care_centre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.station'),
        ),
        migrations.CreateModel(
            name='Mortality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('date_created', models.DateField(auto_now_add=True)),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Morbidity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('Mild (uncomplecated)', 'Mild (uncomplecated)'), ('Moderate (uncomplecated)', 'Moderate (uncomplecated)'), ('Severe (complecated)', 'Severe (complecated)')], max_length=50)),
                ('mode_of_admission', models.CharField(choices=[('Hospitilized', 'Hospitalized'), ('Home Treatment', 'Home Treatment')], max_length=50)),
                ('comment', models.TextField(max_length=5000)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.patient')),
            ],
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='patient_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.patient'),
        ),
    ]
