# Generated by Django 3.2.18 on 2023-05-07 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='follow_up',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app.diagnosis'),
        ),
    ]
