# Generated by Django 3.2.18 on 2023-05-07 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_treatment_follow_up'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mortality',
            name='status',
            field=models.CharField(choices=[('Mortality', 'Mortality'), ('Healed/Discharge', 'Healed/Discharge')], max_length=50),
        ),
    ]
