# Generated by Django 3.2.19 on 2023-05-24 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_mortality_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='family_size',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='no_of_children',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='sleeping_in_screen',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='use_of_insecticide',
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='dianosis_type',
            field=models.CharField(choices=[('Physical Examination', 'Physical Examination'), ('RDT', 'RDT'), ('Microscopy', 'Microscopy'), ('PCR', 'PCR'), ('Combination', 'Combination')], max_length=50),
        ),
        migrations.AlterField(
            model_name='station',
            name='category',
            field=models.CharField(choices=[('Hospital', 'Hospital'), ('Clinic', 'Clinic'), ('Laboratory', 'Laboratory'), ('Mass Screening', 'Mass Screening'), ('Community Camp', 'Community Camp')], max_length=50),
        ),
        migrations.CreateModel(
            name='Preventive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_of_mosquito_net', models.BooleanField()),
                ('use_of_insecticide', models.BooleanField()),
                ('use_of_repellant', models.BooleanField()),
                ('indoor_residual', models.CharField(choices=[('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('6 Months', '6 Months'), ('Annually', 'Annually')], max_length=50)),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_size', models.IntegerField()),
                ('no_of_children', models.IntegerField()),
                ('sleeping_in_screen', models.BooleanField()),
                ('drainage_system', models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], max_length=50)),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.patient')),
            ],
        ),
    ]
