# Generated by Django 4.2.2 on 2023-07-16 06:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaigns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_type', models.CharField(choices=[('Mass Screening', 'Mass Screening'), ('Community Camp', 'Community Camp')], max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('Governmental', 'Governmental'), ('Non-Governmental Organisation', 'Non-Governmental Organisation'), ('Private Organisation', 'Private Organisation'), ('Community Initiative', 'Community Initiative')], max_length=50)),
                ('gis_location', models.CharField(max_length=50)),
                ('address', models.TextField(max_length=200)),
                ('supervisor', models.TextField(max_length=200)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=200)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_date', models.DateField(auto_now_add=True, null=True)),
                ('mode_of_diagnosis', models.CharField(choices=[('New Diagnosis', 'New Diagnosis'), ('Follow Up Diangosis', 'Follow Up Diagnosis')], max_length=50)),
                ('dianosis_type', models.CharField(choices=[('Physical Examination', 'Physical Examination'), ('RDT', 'RDT'), ('Microscopy', 'Microscopy'), ('PCR', 'PCR'), ('Combination', 'Combination')], max_length=50)),
                ('results', models.CharField(choices=[('Positive', 'Positive'), ('Negative', 'Negative')], max_length=50)),
                ('malaria_type', models.CharField(choices=[('P. falciparum', 'P. falciparum'), ('P. vivae', 'P. vivae'), ('P. ovale', 'P. ovale'), ('P. malariae', 'P. malariae')], max_length=50)),
                ('parasitemia_load', models.CharField(max_length=50)),
                ('comment', models.TextField(max_length=5000)),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=50)),
                ('age', models.CharField(max_length=50)),
                ('address', models.TextField(max_length=200)),
                ('opening_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('Hospital', 'Hospital'), ('Clinic', 'Clinic'), ('Laboratory', 'Laboratory')], max_length=50)),
                ('gis_location', models.CharField(max_length=50)),
                ('address', models.TextField(max_length=200)),
                ('supervisor', models.TextField(max_length=200)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=200)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='User_admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment_type', models.CharField(choices=[('ACTs', 'ACTs'), ('Non ACTs', 'Non ACTs'), ('Others', 'Others')], max_length=50)),
                ('treatment_period', models.CharField(choices=[('3 Days', '3 Days'), ('7 Days', '7 Days'), ('14 Days', '14 Days')], max_length=50)),
                ('further_treatment', models.BooleanField()),
                ('comment', models.TextField(max_length=5000)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('follow_up', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app.diagnosis')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.patient')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Station_admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.station')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=200, null=True)),
                ('phone', models.IntegerField(null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Preventive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_of_mosquito_net', models.BooleanField()),
                ('use_of_insecticide', models.BooleanField()),
                ('use_of_repellant', models.BooleanField()),
                ('indoor_residual', models.CharField(choices=[('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('6 Months', '6 Months'), ('Annually', 'Annually')], max_length=50)),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.patient')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='care_centre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.station'),
        ),
        migrations.AddField(
            model_name='patient',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Mortality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Mortality', 'Mortality'), ('Healed/Discharge', 'Healed/Discharge')], max_length=50)),
                ('date', models.DateField()),
                ('date_created', models.DateField(auto_now_add=True)),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.patient')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Morbidity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('Mild (uncomplecated)', 'Mild (uncomplecated)'), ('Moderate (uncomplecated)', 'Moderate (uncomplecated)'), ('Severe (complecated)', 'Severe (complecated)')], max_length=50)),
                ('mode_of_admission', models.CharField(choices=[('Hospitilized', 'Hospitalized'), ('Home Treatment', 'Home Treatment')], max_length=50)),
                ('comment', models.TextField(max_length=5000)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.patient')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_size', models.IntegerField()),
                ('no_of_children', models.IntegerField()),
                ('sleeping_in_screen', models.BooleanField()),
                ('drainage_system', models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], max_length=50)),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.patient')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='patient_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.patient'),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CampReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screened', models.IntegerField()),
                ('treated', models.IntegerField()),
                ('referral', models.IntegerField()),
                ('date_created', models.DateField(auto_now_add=True)),
                ('campaign_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.campaigns')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
