# Generated by Django 4.2.2 on 2023-07-07 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_station_admin_alter_station_supervisor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='supervisor',
            field=models.TextField(max_length=200),
        ),
    ]
