# Generated by Django 4.2.2 on 2023-07-23 06:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_treatment_follow_up'),
    ]

    operations = [
        migrations.AddField(
            model_name='preventive',
            name='date_reported',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
